#!/bin/bash

. /usr/local/etc/allstar.env
#sleep 1
echo "$(date '+%F %T')- $0 $*">>/dev/shm/remote.log

# parse the command line input
INPUT=$1
CMD=${INPUT:0:1}
DATA=${INPUT:1}

# set the radio id for hamlib
# IC-7000
#RADIO="360"
# IC-7100
RADIO="3070"

# have to give the node number to use asterisk commands
# set it expicitly here or...
#ACCESS_NODE=46874
# use the one defined as NODE1 in the allstar env
ACCESS_NODE=${NODE1}

# Define the radio node here. Should be on same CPU
RADIO_NODE="1700"

# Define the serial port here.
# This is the onboard TTL (3.3v) serial port available on the 40 pin header
# You can use it for TTL level stuff but must disable it from use by the OS first.
#SERIAL="/dev/ttyAMA0"
# Usually it is /dev/ttyUSB0 for the first USB adapter
SERIAL="/dev/ttyUSB0"
# Usually it is /dev/ttyUSB1 for the second USB adapter
#SERIAL="/dev/ttyUSB1"

# set for the baud you have your radio configured for
BAUD="19200"

# Wait for radio node to stop tranmitting
function DiscRadioWaitNoTx () {
    echo "$(date '+%F %T')-DiscRadioWaitNoTx">>/dev/shm/remote.log
    asterisk -rx "rpt fun ${ACCESS_NODE} *71${RADIO_NODE}"
    asterisk -rx "rpt fun ${ACCESS_NODE} *1${RADIO_NODE}"
    sleep 1
    while [ -f /dev/shm/out${RADIO_NODE} ]; do
        sleep 0.5
    done;
    echo "$(date '+%F %T')-DiscRadioWaitNoTx return">>/dev/shm/remote.log
}

function SetDigital () {
    echo "$(date '+%F %T')-SetDigital">>/dev/shm/remote.log
    local myRTN=$(rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} m)
#   echo $myRTN
    local myMODE=$(echo ${myRTN} | cut -d' ' -f1)
    local myFILTER=$(echo ${myRTN} | cut -d' ' -f2)
    echo "Mode: ${myMODE}"
    echo "Filter: ${myFILTER}"
    if [ "D-STAR" == ${myMODE} ]; then
        # which means can't access D-STAR remotely either
        echo "$(date '+%F %T')-SetDigital return 1">>/dev/shm/remote.log
        return
    fi
    if [ "PKT" == "${myMODE:0:3}" ]; then
        if ! $1; then
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} M ${myMODE:3} ${myFILTER}
        fi
        echo "$(date '+%F %T')-SetDigital return 2">>/dev/shm/remote.log
        return
    elif $1; then
        rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} M "PKT"${myMODE} ${myFILTER}
    fi
    echo "$(date '+%F %T')-SetDigital return 3">>/dev/shm/remote.log
}

# Increment squelch until closed then add last argument as fudge.
function AutoSquelch () {
    echo "$(date '+%F %T')-AutoSquelch">>/dev/shm/remote.log
    asterisk -rx "rpt fun ${ACCESS_NODE} *2${RADIO_NODE}"
    local FUDGE=$1
    local SQL_LEVEL=0
    echo "Searching for threshold..."
    for i in {0..100}; do
        SQL_LEVEL=$(echo "scale=2;${i}/100" | bc -l)
#        echo $SQL_LEVEL
        rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} L SQL ${SQL_LEVEL}
        [ -f /dev/shm/in${RADIO_NODE} ] || break
    done
    # add fudge
    SQL_LEVEL=$(echo "scale=2; ${SQL_LEVEL}+${FUDGE}/100" | bc -l)
    echo "Setting squelch to $SQL_LEVEL"
    rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} L SQL ${SQL_LEVEL}
    echo "$(date '+%F %T')-AutoSquelch return ${SQL_LEVEL}">>/dev/shm/remote.log
    asterisk -rx "rpt fun ${ACCESS_NODE} *1${RADIO_NODE}"
    
}

# Read the frequency from the radio and speak it.
# Counts the length to determine how to say it
# assuming the number is full Hz value
function SayFreq () {
    echo "$(date '+%F %T')-SayFreq">>/dev/shm/remote.log
    echo "SayFreq"
    #wait to stop NOT echoing tones but keying
    asterisk -rx "rpt fun ${ACCESS_NODE} *71${RADIO_NODE}"
    asterisk -rx "rpt fun ${ACCESS_NODE} *1${RADIO_NODE}"
    FREQ=$(rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} f)
    echo "FREQ: $FREQ"
    FREQLEN=${#FREQ}
    case $FREQLEN in
    9) #like 147330000
        speaktext.sh -g " ${FREQ:0:3},${FREQ:3:3}.${FREQ:6:3}" ${ACCESS_NODE}
    ;;
    8) #like 50125000
        speaktext.sh -g " ${FREQ:0:2},${FREQ:2:3}.${FREQ:5:3}" ${ACCESS_NODE}
    ;;
    7) #like 3975000
        speaktext.sh -g " ${FREQ:0:1},${FREQ:1:3}.${FREQ:4:3}" ${ACCESS_NODE}
    ;;
    6) #like 620000
        speaktext.sh -g " ${FREQ:0:3}.${FREQ:3:3}" ${ACCESS_NODE}
    ;;
    5) #like 25000
        speaktext.sh -g " ${FREQ:0:2}.${FREQ:2:3}" ${ACCESS_NODE}
    ;;
    *) #like anything else
        speaktext.sh -g " ${FREQ}" ${ACCESS_NODE}
    ;;
    esac
    #reconnect after speaking finishes
    (sleep 2; while [ -f /dev/shm/out${ACCESS_NODE} ];do sleep 1; done; asterisk -rx "rpt fun ${ACCESS_NODE} *3${RADIO_NODE}";  echo "$(date '+%F %T')-SayFreq delayed connect">>/dev/shm/remote.log) &
    echo "$(date '+%F %T')-SayFreq exit">>/dev/shm/remote.log
}

function SetRadio () {
    echo "$(date '+%F %T')-SetRadio enter">>/dev/shm/remote.log
    DiscRadioWaitNoTx
    case $CMD in
        0) #say freq
            SayFreq
        ;;
        1)	#select bank,mem,mem
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} V MEM B ${DATA:0:1} E ${DATA:1}
            # SayFreq
        ;;
        2)  #step up nnn Hz *622100 steps up 100 Hz (3 digit max)
            FREQ=$(rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} f)
            echo ${FREQ}
            let FREQ=${FREQ}+${DATA}
            echo ${FREQ}
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} F ${FREQ}
            # SayFreq
        ;;
        3)  #step down nnn Hz - *623010 steps down 10 Hz (3 digit max)
            FREQ=$(rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} f)
            let FREQ=$FREQ-${DATA}
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} F ${FREQ}
            # SayFreq
        ;;
        4)  #LSB mode (IC-7000 requires filter width with mode)
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} M LSB 2400
        ;;
        5)  #USB mode (IC-7000 requires filter width with mode)
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} M USB 2400
        ;;
        6)  #FM mode (IC-7000 requires filter width with mode)
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} M FM 15000
        ;;
        7)  #AM mode (IC-7000 requires filter width with mode)
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} M AM 6000
        ;;
        8)  #Misc functions
            SUB_CMD=${DATA:0:1}
            SUB_DATA=${DATA:1}
            echo "Misc: >${SUB_CMD}< >${SUB_DATA}<">>/dev/shm/remote.log
            case $SUB_CMD in
                0)  #Select VFO A or B (0 or 1)
                    rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} V VFO
                    if [ "${SUB_DATA:0:1}" == "1" ] ; then
                        rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} V VFOA
                    elif [ "${SUB_DATA:0:1}" == "2" ] ; then
                        rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} V VFOB
                    fi
                ;;
                9)  #tuner set
                    echo "tune"
                    rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} G TUNE
                ;;
            esac
        ;;
        9) #set squelch
            if [ "${DATA:0:1}" == "0" ] || [ "$DATA:0:1}" == "1" ]; then
                rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} L SQL ${DATA:0:1}.${DATA:1}
            elif [ "${DATA:0:1}" == 9 ]; then
                AutoSquelch ${DATA:1}
            fi
        ;;
        T) #pass on param for testing
            rigctl -m ${RADIO} -r ${SERIAL} -s ${BAUD} ${DATA}
        ;;
    esac
    SetDigital true
    asterisk -rx "rpt fun ${ACCESS_NODE} *3${RADIO_NODE}"
    echo "$(date '+%F %T')-SetRadio exit">>/dev/shm/remote.log
}

# work actually starts here...
SetRadio

exit 0
